# DevKit Funding & Support

# Primary funding (Gumroad)
custom: ["https://yourgumroad.com/l/devkit", "Buy Pre-Built Binaries"]

# GitHub Sponsors (if/when enabled)
# github: [bobinzuks]

# Alternative platforms (optional)
# ko_fi: bobinzuks
# patreon: bobinzuks
# buy_me_a_coffee: bobinzuks
